name: SnakeTV
options:
  bundleIdPrefix: com.snakeio
  deploymentTarget:
    tvOS: "16.0"
  xcodeVersion: "15.0"

targets:
  SnakeTV:
    type: application
    platform: tvOS
    sources:
      - path: Sources
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.snakeio.tv
        MARKETING_VERSION: "1.0.0"
        CURRENT_PROJECT_VERSION: 1
        INFOPLIST_FILE: Info.plist
        FRAMEWORK_SEARCH_PATHS:
          - "$(PROJECT_DIR)/../Frameworks/Mobile-tvOS.xcframework"
          - "$(PROJECT_DIR)/../Frameworks"
        OTHER_LDFLAGS:
          - "-ObjC"
        SWIFT_OBJC_BRIDGING_HEADER: ""
    dependencies:
      - framework: "../Frameworks/Mobile-tvOS.xcframework"
        embed: true
