name: SnakeTV
options:
  bundleIdPrefix: com.schlangen
  deploymentTarget:
    tvOS: "16.0"
  xcodeVersion: "15.0"

targets:
  SnakeTV:
    type: application
    platform: tvOS
    sources:
      - path: Sources
      - path: Assets.xcassets
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.schlangen.tv
        MARKETING_VERSION: "1.0.0"
        CURRENT_PROJECT_VERSION: 1
        INFOPLIST_FILE: Info.plist
        ASSETCATALOG_COMPILER_APPICON_NAME: "Brand Assets"
        FRAMEWORK_SEARCH_PATHS:
          - "$(PROJECT_DIR)/../Frameworks/Mobile-tvOS.xcframework"
          - "$(PROJECT_DIR)/../Frameworks"
        OTHER_LDFLAGS:
          - "-ObjC"
        SWIFT_OBJC_BRIDGING_HEADER: ""
    dependencies:
      - framework: "../Frameworks/Mobile-tvOS.xcframework"
        embed: true
